// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMqcrDs56KUzX1LU7AUu-xUd9AaYRWi30',
    appId: '1:249688389087:web:4cb7be032233e6d80a406a',
    messagingSenderId: '249688389087',
    projectId: 'travelvibe-c0f03',
    authDomain: 'travelvibe-c0f03.firebaseapp.com',
    storageBucket: 'travelvibe-c0f03.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGVfAkEYCgG0AFu9YSCXY2Gw0n3y2tKg8',
    appId: '1:249688389087:android:c4177e9ff9ce8e450a406a',
    messagingSenderId: '249688389087',
    projectId: 'travelvibe-c0f03',
    storageBucket: 'travelvibe-c0f03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB25zZyCnrVTQHMzRYvSx_eW5sreiKQb6k',
    appId: '1:249688389087:ios:5598ce6edb967bfc0a406a',
    messagingSenderId: '249688389087',
    projectId: 'travelvibe-c0f03',
    storageBucket: 'travelvibe-c0f03.appspot.com',
    iosClientId: '249688389087-31j0fsi691umun73tkqafsneas0vbveu.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelVibeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB25zZyCnrVTQHMzRYvSx_eW5sreiKQb6k',
    appId: '1:249688389087:ios:7f0478e1eed4569a0a406a',
    messagingSenderId: '249688389087',
    projectId: 'travelvibe-c0f03',
    storageBucket: 'travelvibe-c0f03.appspot.com',
    iosClientId: '249688389087-upi70809usu953fov8tdi9f289eliufg.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelVibeApp.RunnerTests',
  );
}
